INFO 2022-06-10 15:37:34,774 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-10 15:38:17,553 basehttp 154 "GET / HTTP/1.1" 200 16348
INFO 2022-06-10 15:38:17,823 basehttp 154 "GET /favicon.ico HTTP/1.1" 200 16348
INFO 2022-06-10 15:41:59,782 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\meiduo_mall\urls.py changed, reloading.
INFO 2022-06-10 15:42:00,649 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-10 15:54:04,058 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2022-06-10 15:54:04,920 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-10 16:05:02,119 basehttp 154 "GET / HTTP/1.1" 200 16348
INFO 2022-06-10 16:05:02,179 basehttp 154 "GET /static/admin/css/fonts.css HTTP/1.1" 200 423
INFO 2022-06-10 16:05:02,344 basehttp 154 "GET /static/admin/fonts/Roboto-Bold-webfont.woff HTTP/1.1" 200 86184
INFO 2022-06-10 16:05:02,345 basehttp 154 "GET /static/admin/fonts/Roboto-Regular-webfont.woff HTTP/1.1" 200 85876
INFO 2022-06-10 16:05:02,349 basehttp 154 "GET /static/admin/fonts/Roboto-Light-webfont.woff HTTP/1.1" 200 85692
INFO 2022-06-10 16:05:02,402 basehttp 154 "GET /favicon.ico HTTP/1.1" 200 16348
INFO 2022-06-10 16:06:55,331 basehttp 154 "GET /carts/simple/ HTTP/1.1" 200 16348
INFO 2022-06-10 16:38:22,390 basehttp 154 "GET /carts/simple/ HTTP/1.1" 200 16348
INFO 2022-06-10 16:38:28,249 basehttp 154 "GET /image_codes/118f9e82-9d04-4dc6-b677-b53a533844f2/ HTTP/1.1" 200 16348
INFO 2022-06-10 16:38:31,975 basehttp 154 "GET /usernames/admin/count/ HTTP/1.1" 200 16348
INFO 2022-06-12 11:06:37,775 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-12 11:07:02,621 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\models.py changed, reloading.
INFO 2022-06-12 11:07:03,489 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-12 11:36:12,822 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\meiduo_mall\urls.py changed, reloading.
INFO 2022-06-12 11:36:13,732 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 08:16:44,633 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 08:18:01,480 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 08:21:08,300 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 08:22:04,273 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 08:22:49,528 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 08:22:54,388 basehttp 154 "GET /usernames/itcast/count HTTP/1.1" 301 0
INFO 2022-06-13 08:22:54,417 basehttp 154 "GET /usernames/itcast/count/ HTTP/1.1" 200 39
INFO 2022-06-13 08:29:25,039 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\meiduo_mall\urls.py changed, reloading.
INFO 2022-06-13 08:29:25,912 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 08:30:01,534 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\urls.py changed, reloading.
INFO 2022-06-13 08:30:02,376 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 08:30:07,070 basehttp 154 "GET /usernames/itcast/count HTTP/1.1" 301 0
INFO 2022-06-13 08:30:07,083 basehttp 154 "GET /usernames/itcast/count/ HTTP/1.1" 200 39
WARNING 2022-06-13 08:30:13,086 log 222 Not Found: /usernames/it/count
WARNING 2022-06-13 08:30:13,086 basehttp 154 "GET /usernames/it/count HTTP/1.1" 404 2081
INFO 2022-06-13 08:39:48,355 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2022-06-13 08:39:49,262 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 08:40:03,369 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2022-06-13 08:40:04,235 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 08:40:55,012 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2022-06-13 08:40:55,919 autoreload 578 Watching for file changes with StatReloader
WARNING 2022-06-13 08:44:04,784 log 222 Not Found: /carts/simple/
WARNING 2022-06-13 08:44:04,785 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2072
WARNING 2022-06-13 08:44:08,105 log 222 Not Found: /image_codes/99ea6f9a-bdbc-4cd8-997f-f5bdf89c86ad/
WARNING 2022-06-13 08:44:08,105 basehttp 154 "GET /image_codes/99ea6f9a-bdbc-4cd8-997f-f5bdf89c86ad/ HTTP/1.1" 404 2180
INFO 2022-06-13 08:44:10,145 basehttp 154 "GET /usernames/itcast/count/ HTTP/1.1" 200 39
INFO 2022-06-13 08:49:13,674 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2022-06-13 08:49:14,620 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 09:04:31,352 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\urls.py changed, reloading.
INFO 2022-06-13 09:04:32,254 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 09:04:45,174 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 09:24:24,506 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2022-06-13 09:24:25,412 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 09:28:10,154 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2022-06-13 09:28:11,020 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 09:28:23,197 basehttp 154 "GET /usernames/itcast/count/ HTTP/1.1" 200 39
WARNING 2022-06-13 09:28:38,963 log 222 Not Found: /mobiles/13977887788/count/
WARNING 2022-06-13 09:28:38,964 basehttp 154 "GET /mobiles/13977887788/count/ HTTP/1.1" 404 2267
INFO 2022-06-13 09:28:52,231 basehttp 154 "GET /usernames/itcast/count/ HTTP/1.1" 200 39
WARNING 2022-06-13 09:28:52,233 log 222 Not Found: /mobiles/13977887788/count/
WARNING 2022-06-13 09:28:52,234 basehttp 154 "GET /mobiles/13977887788/count/ HTTP/1.1" 404 2267
INFO 2022-06-13 09:28:52,242 basehttp 154 "OPTIONS /register/ HTTP/1.1" 200 0
INFO 2022-06-13 09:29:36,629 basehttp 154 "GET /usernames/itcast/count/ HTTP/1.1" 200 39
WARNING 2022-06-13 09:29:37,923 log 222 Not Found: /mobiles/13977887788/count/
WARNING 2022-06-13 09:29:38,112 basehttp 154 "GET /mobiles/13977887788/count/ HTTP/1.1" 404 2267
ERROR 2022-06-13 09:29:43,973 log 222 Internal Server Error: /register/
Traceback (most recent call last):
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\HADOOPIMAGE\AppData\Local\Programs\Python\Python38\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\HADOOPIMAGE\AppData\Local\Programs\Python\Python38\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\HADOOPIMAGE\AppData\Local\Programs\Python\Python38\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb._exceptions.IntegrityError: (1062, "Duplicate entry 'itcast' for key 'tb_users.username'")

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\views.py", line 122, in post
    user = User.objects.create_user(
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\models.py", line 151, in create_user
    return self._create_user(username, email, password, **extra_fields)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\models.py", line 145, in _create_user
    user.save(using=self._db)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\base_user.py", line 66, in save
    super().save(*args, **kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\db\models\base.py", line 740, in save
    self.save_base(using=using, force_insert=force_insert,
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\db\models\base.py", line 777, in save_base
    updated = self._save_table(
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\db\models\base.py", line 870, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\db\models\base.py", line 907, in _do_insert
    return manager._insert([self], fields=fields, return_id=update_pk,
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\db\models\manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\db\models\query.py", line 1186, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\db\models\sql\compiler.py", line 1332, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\db\backends\utils.py", line 99, in execute
    return super().execute(sql, params)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\db\backends\utils.py", line 76, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\db\utils.py", line 89, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\db\backends\utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\db\backends\mysql\base.py", line 71, in execute
    return self.cursor.execute(query, args)
  File "C:\Users\HADOOPIMAGE\AppData\Local\Programs\Python\Python38\lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
  File "C:\Users\HADOOPIMAGE\AppData\Local\Programs\Python\Python38\lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\HADOOPIMAGE\AppData\Local\Programs\Python\Python38\lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
django.db.utils.IntegrityError: (1062, "Duplicate entry 'itcast' for key 'tb_users.username'")
INFO 2022-06-13 09:29:44,189 basehttp 154 "GET /usernames/itcast01/count/ HTTP/1.1" 200 39
ERROR 2022-06-13 09:29:46,364 basehttp 154 "POST /register/ HTTP/1.1" 500 207840
WARNING 2022-06-13 09:29:50,090 log 222 Not Found: /mobiles/13977887789/count/
WARNING 2022-06-13 09:29:50,231 basehttp 154 "GET /mobiles/13977887789/count/ HTTP/1.1" 404 2267
WARNING 2022-06-13 09:29:57,833 log 222 Not Found: /mobiles/13977887789/count/
WARNING 2022-06-13 09:29:57,956 basehttp 154 "GET /mobiles/13977887789/count/ HTTP/1.1" 404 2267
INFO 2022-06-13 09:30:06,241 basehttp 154 "GET /usernames/itcast01/count/ HTTP/1.1" 200 39
WARNING 2022-06-13 09:30:06,621 log 222 Not Found: /mobiles/13977887789/count/
WARNING 2022-06-13 09:30:06,700 basehttp 154 "GET /mobiles/13977887789/count/ HTTP/1.1" 404 2267
WARNING 2022-06-13 09:35:58,956 log 222 Not Found: /carts/simple/
WARNING 2022-06-13 09:35:59,194 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2228
ERROR 2022-06-13 09:54:16,212 basehttp 154 "POST /register/ HTTP/1.1" 500 59
ERROR 2022-06-13 09:54:16,225 basehttp 154 "POST /register/ HTTP/1.1" 500 59
INFO 2022-06-13 10:15:37,923 autoreload 578 Watching for file changes with StatReloader
WARNING 2022-06-13 10:16:29,637 log 222 Not Found: /image_codes/123/
WARNING 2022-06-13 10:16:29,638 basehttp 154 "GET /image_codes/123/ HTTP/1.1" 404 2231
WARNING 2022-06-13 10:16:29,901 log 222 Not Found: /favicon.ico
WARNING 2022-06-13 10:16:29,902 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 2216
INFO 2022-06-13 10:17:11,383 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\meiduo_mall\urls.py changed, reloading.
INFO 2022-06-13 10:17:12,334 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 10:17:20,893 basehttp 154 "GET /image_codes/123/ HTTP/1.1" 200 2970
INFO 2022-06-13 10:20:43,263 basehttp 154 "GET /image_codes/2b44267c-8384-4e22-84c7-4d9430e47c5f/ HTTP/1.1" 200 3402
INFO 2022-06-13 10:21:00,204 basehttp 154 "GET /image_codes/ec150549-77f7-4c32-8faf-35332b542320/ HTTP/1.1" 200 3211
INFO 2022-06-13 10:21:00,803 basehttp 154 "GET /image_codes/3d1c3d5e-a39c-494b-8489-f9d4de6b4fbe/ HTTP/1.1" 200 3552
INFO 2022-06-13 10:21:01,299 basehttp 154 "GET /image_codes/50e113ed-c015-4314-8a2f-b732cf859218/ HTTP/1.1" 200 3204
INFO 2022-06-13 10:21:03,042 basehttp 154 "GET /image_codes/608f0c32-5056-4e01-a7b7-1eecf0dc4b42/ HTTP/1.1" 200 3165
INFO 2022-06-13 10:21:03,772 basehttp 154 "GET /image_codes/3da3e1f2-b2c3-4030-ae97-fe3d9497d415/ HTTP/1.1" 200 3023
INFO 2022-06-13 10:21:10,264 basehttp 154 "GET /image_codes/961a2799-0dcf-49f9-a0ec-4ae923816703/ HTTP/1.1" 200 3166
INFO 2022-06-13 10:21:11,221 basehttp 154 "GET /image_codes/7f25745d-cd03-4d0c-aa20-90b8f8928eea/ HTTP/1.1" 200 3377
INFO 2022-06-13 10:21:12,109 basehttp 154 "GET /image_codes/0ee047b6-eb85-4af3-a3da-f74d171a016b/ HTTP/1.1" 200 3095
INFO 2022-06-13 11:15:52,781 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 11:54:02,494 basehttp 154 "GET /usernames/itcast111/count/ HTTP/1.1" 200 39
WARNING 2022-06-13 11:54:13,928 log 222 Not Found: /mobiles/18019966096/count/
WARNING 2022-06-13 11:54:13,929 basehttp 154 "GET /mobiles/18019966096/count/ HTTP/1.1" 404 2611
INFO 2022-06-13 11:54:14,008 basehttp 154 "GET /image_codes/fc848a7a-9fc5-4058-bee7-35051b233326/ HTTP/1.1" 200 3297
WARNING 2022-06-13 11:54:20,116 log 222 Not Found: /mobiles/18019966096/count/
WARNING 2022-06-13 11:54:20,117 basehttp 154 "GET /mobiles/18019966096/count/ HTTP/1.1" 404 2611
INFO 2022-06-13 11:54:20,380 basehttp 154 "GET /sms_codes/18019966096/?image_code=BGHN&image_code_id=fc848a7a-9fc5-4058-bee7-35051b233326 HTTP/1.1" 200 27
WARNING 2022-06-13 11:55:19,185 log 222 Not Found: /mobiles/18019966096/count/
INFO 2022-06-13 11:55:19,185 basehttp 154 "OPTIONS /register/ HTTP/1.1" 200 0
WARNING 2022-06-13 11:55:19,186 basehttp 154 "GET /mobiles/18019966096/count/ HTTP/1.1" 404 2611
INFO 2022-06-13 11:55:19,189 basehttp 154 "GET /usernames/itcast111/count/ HTTP/1.1" 200 39
INFO 2022-06-13 11:55:19,342 basehttp 154 "POST /register/ HTTP/1.1" 200 27
WARNING 2022-06-13 11:55:19,748 log 222 Not Found: /carts/simple/
WARNING 2022-06-13 11:55:19,749 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2572
INFO 2022-06-13 14:00:05,638 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2022-06-13 14:00:08,400 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 14:00:15,398 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\urls.py changed, reloading.
INFO 2022-06-13 14:00:15,407 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\urls.py changed, reloading.
INFO 2022-06-13 14:00:16,428 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 14:00:17,819 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 14:09:11,267 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 14:09:34,840 basehttp 154 "OPTIONS /login/ HTTP/1.1" 200 0
INFO 2022-06-13 14:09:35,048 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2022-06-13 14:09:35,435 log 222 Not Found: /carts/simple/
WARNING 2022-06-13 14:09:35,436 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2725
INFO 2022-06-13 14:19:05,471 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2022-06-13 14:19:05,859 log 222 Not Found: /carts/simple/
WARNING 2022-06-13 14:19:05,860 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 2725
WARNING 2022-06-13 14:19:13,092 log 222 Not Found: /info/
WARNING 2022-06-13 14:19:13,094 log 222 Not Found: /browse_histories/
WARNING 2022-06-13 14:19:13,095 basehttp 154 "GET /info/ HTTP/1.1" 404 2701
WARNING 2022-06-13 14:19:13,096 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 2737
INFO 2022-06-13 14:19:17,260 basehttp 154 "OPTIONS /logout/ HTTP/1.1" 200 0
WARNING 2022-06-13 14:19:17,265 log 222 Not Found: /logout/
WARNING 2022-06-13 14:19:17,266 basehttp 154 "DELETE /logout/ HTTP/1.1" 404 2710
WARNING 2022-06-13 14:19:24,373 log 222 Not Found: /logout/
WARNING 2022-06-13 14:19:24,374 basehttp 154 "DELETE /logout/ HTTP/1.1" 404 2710
INFO 2022-06-13 14:23:51,181 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2022-06-13 14:23:52,064 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 14:43:44,208 autoreload 578 Watching for file changes with StatReloader
WARNING 2022-06-13 14:43:50,748 base 100 Method Not Allowed (DELETE): /logout/
WARNING 2022-06-13 14:43:50,751 log 222 Method Not Allowed: /logout/
WARNING 2022-06-13 14:43:50,752 basehttp 154 "DELETE /logout/ HTTP/1.1" 405 0
WARNING 2022-06-13 14:43:51,580 base 100 Method Not Allowed (DELETE): /logout/
WARNING 2022-06-13 14:43:51,581 log 222 Method Not Allowed: /logout/
WARNING 2022-06-13 14:43:51,582 basehttp 154 "DELETE /logout/ HTTP/1.1" 405 0
WARNING 2022-06-13 14:44:40,707 base 100 Method Not Allowed (DELETE): /logout/
WARNING 2022-06-13 14:44:40,708 log 222 Method Not Allowed: /logout/
WARNING 2022-06-13 14:44:40,708 basehttp 154 "DELETE /logout/ HTTP/1.1" 405 0
WARNING 2022-06-13 14:44:45,607 log 222 Not Found: /carts/simple/
WARNING 2022-06-13 14:44:45,609 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3031
WARNING 2022-06-13 14:44:48,492 log 222 Not Found: /browse_histories/
WARNING 2022-06-13 14:44:48,493 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3043
ERROR 2022-06-13 14:44:48,528 log 222 Internal Server Error: /info/
Traceback (most recent call last):
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\views.py", line 281, in get
    'email_active': request.user.email_active,
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\utils\functional.py", line 257, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'email_active'
ERROR 2022-06-13 14:44:48,530 basehttp 154 "GET /info/ HTTP/1.1" 500 89217
INFO 2022-06-13 14:44:51,602 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2022-06-13 14:44:51,847 log 222 Not Found: /carts/simple/
WARNING 2022-06-13 14:44:51,848 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3031
WARNING 2022-06-13 14:44:54,274 base 100 Method Not Allowed (DELETE): /logout/
WARNING 2022-06-13 14:44:54,275 log 222 Method Not Allowed: /logout/
WARNING 2022-06-13 14:44:54,276 basehttp 154 "DELETE /logout/ HTTP/1.1" 405 0
WARNING 2022-06-13 14:44:54,972 base 100 Method Not Allowed (DELETE): /logout/
WARNING 2022-06-13 14:44:54,973 log 222 Method Not Allowed: /logout/
WARNING 2022-06-13 14:44:54,973 basehttp 154 "DELETE /logout/ HTTP/1.1" 405 0
WARNING 2022-06-13 14:44:56,099 base 100 Method Not Allowed (DELETE): /logout/
WARNING 2022-06-13 14:44:56,100 log 222 Method Not Allowed: /logout/
WARNING 2022-06-13 14:44:56,101 basehttp 154 "DELETE /logout/ HTTP/1.1" 405 0
INFO 2022-06-13 14:47:06,265 autoreload 578 Watching for file changes with StatReloader
WARNING 2022-06-13 14:47:12,708 base 100 Method Not Allowed (DELETE): /logout/
WARNING 2022-06-13 14:47:12,711 log 222 Method Not Allowed: /logout/
WARNING 2022-06-13 14:47:12,711 basehttp 154 "DELETE /logout/ HTTP/1.1" 405 0
WARNING 2022-06-13 14:53:38,437 base 100 Method Not Allowed (DELETE): /logout/
WARNING 2022-06-13 14:53:38,438 log 222 Method Not Allowed: /logout/
WARNING 2022-06-13 14:53:38,439 basehttp 154 "DELETE /logout/ HTTP/1.1" 405 0
WARNING 2022-06-13 14:55:42,132 base 100 Method Not Allowed (DELETE): /logout/
WARNING 2022-06-13 14:55:42,133 log 222 Method Not Allowed: /logout/
WARNING 2022-06-13 14:55:42,133 basehttp 154 "DELETE /logout/ HTTP/1.1" 405 0
INFO 2022-06-13 14:58:10,176 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2022-06-13 14:58:11,109 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 14:58:13,388 basehttp 154 "DELETE /logout/ HTTP/1.1" 200 27
INFO 2022-06-13 14:58:51,775 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2022-06-13 14:58:52,149 log 222 Not Found: /carts/simple/
WARNING 2022-06-13 14:58:52,150 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3031
WARNING 2022-06-13 14:58:57,157 log 222 Not Found: /browse_histories/
WARNING 2022-06-13 14:58:57,158 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3043
ERROR 2022-06-13 14:58:57,188 log 222 Internal Server Error: /info/
Traceback (most recent call last):
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\views.py", line 281, in get
    'email_active': request.user.email_active,
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\utils\functional.py", line 257, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'email_active'
ERROR 2022-06-13 14:58:57,191 basehttp 154 "GET /info/ HTTP/1.1" 500 89217
INFO 2022-06-13 14:59:01,026 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2022-06-13 14:59:01,341 log 222 Not Found: /carts/simple/
WARNING 2022-06-13 14:59:01,342 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3031
WARNING 2022-06-13 14:59:03,482 log 222 Not Found: /browse_histories/
WARNING 2022-06-13 14:59:03,490 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3043
ERROR 2022-06-13 14:59:03,514 log 222 Internal Server Error: /info/
Traceback (most recent call last):
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\views.py", line 281, in get
    'email_active': request.user.email_active,
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\utils\functional.py", line 257, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'email_active'
ERROR 2022-06-13 14:59:03,515 basehttp 154 "GET /info/ HTTP/1.1" 500 89217
INFO 2022-06-13 15:00:49,792 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\models.py changed, reloading.
INFO 2022-06-13 15:00:50,676 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 15:04:37,672 basehttp 154 "POST /login/ HTTP/1.1" 200 27
WARNING 2022-06-13 15:04:38,077 log 222 Not Found: /carts/simple/
WARNING 2022-06-13 15:04:38,077 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3031
WARNING 2022-06-13 15:04:39,475 log 222 Not Found: /browse_histories/
INFO 2022-06-13 15:04:39,476 basehttp 154 "GET /info/ HTTP/1.1" 200 128
WARNING 2022-06-13 15:04:39,477 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3043
INFO 2022-06-13 15:10:23,686 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2022-06-13 15:10:24,564 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 15:36:27,050 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2022-06-13 15:36:27,967 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 15:44:06,468 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 15:45:20,454 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 15:46:29,436 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 15:47:10,550 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 15:47:42,987 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 16:02:52,904 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 16:02:58,508 basehttp 154 "OPTIONS /emails/ HTTP/1.1" 200 0
ERROR 2022-06-13 16:02:58,653 log 222 Internal Server Error: /emails/
Traceback (most recent call last):
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\views.py", line 340, in put
    from apps.users.utils import generic_email_verify_token
  File "E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\utils.py", line 1, in <module>
    from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
ImportError: cannot import name 'TimedJSONWebSignatureSerializer' from 'itsdangerous' (C:\Users\HADOOPIMAGE\AppData\Local\Programs\Python\Python38\lib\site-packages\itsdangerous\__init__.py)
ERROR 2022-06-13 16:02:58,655 basehttp 154 "PUT /emails/ HTTP/1.1" 500 97655
ERROR 2022-06-13 16:04:08,629 log 222 Internal Server Error: /emails/
Traceback (most recent call last):
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\views.py", line 340, in put
    from apps.users.utils import generic_email_verify_token
  File "E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\utils.py", line 1, in <module>
    from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
ImportError: cannot import name 'TimedJSONWebSignatureSerializer' from 'itsdangerous' (C:\Users\HADOOPIMAGE\AppData\Local\Programs\Python\Python38\lib\site-packages\itsdangerous\__init__.py)
ERROR 2022-06-13 16:04:08,630 basehttp 154 "PUT /emails/ HTTP/1.1" 500 97655
INFO 2022-06-13 16:04:54,599 autoreload 578 Watching for file changes with StatReloader
ERROR 2022-06-13 16:04:55,620 log 222 Internal Server Error: /emails/
Traceback (most recent call last):
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\contrib\auth\mixins.py", line 52, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "C:\Users\HADOOPIMAGE\AppData\Roaming\Python\Python38\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\views.py", line 340, in put
    from apps.users.utils import generic_email_verify_token
  File "E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\utils.py", line 1, in <module>
    from itsdangerous import TimedJSONWebSignatureSerializer as Serializer
ImportError: cannot import name 'TimedJSONWebSignatureSerializer' from 'itsdangerous' (C:\Users\HADOOPIMAGE\AppData\Local\Programs\Python\Python38\lib\site-packages\itsdangerous\__init__.py)
ERROR 2022-06-13 16:04:55,622 basehttp 154 "PUT /emails/ HTTP/1.1" 500 97655
INFO 2022-06-13 16:05:16,951 autoreload 578 Watching for file changes with StatReloader
WARNING 2022-06-13 16:09:18,482 log 222 Not Found: /carts/
WARNING 2022-06-13 16:09:18,483 basehttp 154 "GET /carts/ HTTP/1.1" 404 3164
INFO 2022-06-13 16:09:19,954 basehttp 154 "GET /info/ HTTP/1.1" 200 149
WARNING 2022-06-13 16:09:19,956 log 222 Not Found: /browse_histories/
WARNING 2022-06-13 16:09:19,957 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3197
WARNING 2022-06-13 16:09:25,094 log 222 Not Found: /carts/simple/
WARNING 2022-06-13 16:09:25,094 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3185
WARNING 2022-06-13 16:09:34,308 log 222 Not Found: /browse_histories/
WARNING 2022-06-13 16:09:34,309 basehttp 154 "GET /browse_histories/ HTTP/1.1" 404 3197
INFO 2022-06-13 16:09:34,311 basehttp 154 "GET /info/ HTTP/1.1" 200 149
WARNING 2022-06-13 16:09:37,544 log 222 Not Found: /addresses/
WARNING 2022-06-13 16:09:37,546 basehttp 154 "GET /addresses/ HTTP/1.1" 404 3176
WARNING 2022-06-13 16:09:37,548 log 222 Not Found: /areas/
WARNING 2022-06-13 16:09:37,553 basehttp 154 "GET /areas/ HTTP/1.1" 404 3164
INFO 2022-06-13 16:15:59,886 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 16:16:44,914 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2022-06-13 16:16:45,027 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2022-06-13 16:16:45,957 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 16:16:47,251 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 16:17:35,739 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\areas\models.py changed, reloading.
INFO 2022-06-13 16:17:36,659 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 16:58:21,375 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\areas\models.py changed, reloading.
INFO 2022-06-13 16:58:23,820 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-13 20:25:45,923 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2022-06-13 20:25:48,418 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-14 08:22:49,687 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-14 08:26:16,816 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2022-06-14 08:26:17,693 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-14 08:26:50,058 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\views.py changed, reloading.
INFO 2022-06-14 08:26:50,933 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-14 08:29:16,283 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\urls.py changed, reloading.
INFO 2022-06-14 08:29:17,207 autoreload 578 Watching for file changes with StatReloader
WARNING 2022-06-14 08:41:42,170 log 222 Not Found: /carts/simple/
WARNING 2022-06-14 08:41:42,171 basehttp 154 "GET /carts/simple/ HTTP/1.1" 404 3342
INFO 2022-06-14 09:17:20,020 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\apps\users\urls.py changed, reloading.
INFO 2022-06-14 09:17:21,050 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-14 09:21:43,949 autoreload 203 E:\Django\meiduo\meiduo\shop_web\meiduo_mall\meiduo_mall\settings.py changed, reloading.
INFO 2022-06-14 09:21:44,882 autoreload 578 Watching for file changes with StatReloader
INFO 2022-06-14 10:34:45,296 autoreload 578 Watching for file changes with StatReloader
WARNING 2022-06-14 10:34:52,988 log 222 Not Found: /
WARNING 2022-06-14 10:34:52,989 basehttp 154 "GET / HTTP/1.1" 404 3607
WARNING 2022-06-14 10:34:53,306 log 222 Not Found: /favicon.ico
WARNING 2022-06-14 10:34:53,306 basehttp 154 "GET /favicon.ico HTTP/1.1" 404 3658
INFO 2022-06-16 02:13:27,927 autoreload 637 Watching for file changes with StatReloader
INFO 2022-06-16 02:14:16,303 autoreload 251 /home/jennifer/桌面/shop_web/meiduo_mall/apps/verifications/apps.py changed, reloading.
INFO 2022-06-16 02:14:16,532 autoreload 637 Watching for file changes with StatReloader
INFO 2022-06-16 02:15:03,304 autoreload 637 Watching for file changes with StatReloader
INFO 2022-06-16 02:17:32,755 autoreload 637 Watching for file changes with StatReloader
INFO 2022-06-16 02:18:00,131 autoreload 637 Watching for file changes with StatReloader
INFO 2022-06-16 02:18:51,373 autoreload 637 Watching for file changes with StatReloader
INFO 2022-06-16 02:19:25,753 autoreload 637 Watching for file changes with StatReloader
INFO 2022-06-16 02:20:15,095 autoreload 637 Watching for file changes with StatReloader
INFO 2022-06-16 02:21:02,628 autoreload 251 /home/jennifer/桌面/shop_web/meiduo_mall/meiduo_mall/settings.py changed, reloading.
INFO 2022-06-16 02:21:02,940 autoreload 637 Watching for file changes with StatReloader
INFO 2022-06-16 02:22:15,386 autoreload 637 Watching for file changes with StatReloader
